[project]
name = "curso-mcp-jseminarioh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.24.0",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
]

[project.scripts]
curso-mcp-jseminarioh = "curso_mcp_jseminarioh:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
